/**
 * Contratos machine-readable derivados de docs/compras-gov/schemas-consultas.md
 * + campos observados nas fixtures reais (tar workspace).
 * Não inventa campos além do documentado / observado.
 */

export type FieldType =
  | "string"
  | "number"
  | "boolean"
  | "date"
  | "date-time"
  | "nullish";

export interface EndpointContract {
  secao: string;
  endpoint: string;
  path: string;
  dto: string;
  /** Campos que devem existir em todo item da amostra */
  requiredKeys: string[];
  /** União de campos documentados + observados (extras na fixture = warn) */
  knownKeys: string[];
  status: "fixture-ok" | "nao-testado" | "live-only";
  fixtureFile?: string;
}

export const ENVELOPE_KEYS = [
  "resultado",
  "totalRegistros",
  "totalPaginas",
  "paginasRestantes",
] as const;

export const CONTRACTS: EndpointContract[] = [
  // --- 01 CATÁLOGO MATERIAL ---
  {
    secao: "01",
    endpoint: "1_consultarGrupoMaterial",
    path: "/modulo-material/1_consultarGrupoMaterial",
    dto: "DmMaterialGrupoDTO",
    requiredKeys: ["codigoGrupo", "nomeGrupo", "statusGrupo"],
    knownKeys: [
      "codigoGrupo",
      "nomeGrupo",
      "statusGrupo",
      "dataHoraAtualizacao",
    ],
    status: "nao-testado",
  },
  {
    secao: "01",
    endpoint: "2_consultarClasseMaterial",
    path: "/modulo-material/2_consultarClasseMaterial",
    dto: "DmMaterialClasseDTO",
    requiredKeys: ["codigoGrupo", "codigoClasse", "nomeClasse", "statusClasse"],
    knownKeys: [
      "codigoGrupo",
      "codigoClasse",
      "nomeGrupo",
      "nomeClasse",
      "statusClasse",
      "dataHoraAtualizacao",
    ],
    status: "fixture-ok",
    fixtureFile: "01/2_consultarClasseMaterial.sample.json",
  },
  {
    secao: "01",
    endpoint: "3_consultarPdmMaterial",
    path: "/modulo-material/3_consultarPdmMaterial",
    dto: "DmMaterialPDMDTO",
    requiredKeys: ["codigoPdm", "codigoGrupo", "codigoClasse", "nomePdm"],
    knownKeys: [
      "codigoPdm",
      "codigoGrupo",
      "codigoClasse",
      "nomePdm",
      "nomeGrupo",
      "nomeClasse",
      "statusPdm",
      "dataHoraAtualizacao",
    ],
    status: "fixture-ok",
    fixtureFile: "01/3_consultarPdmMaterial.sample.json",
  },
  {
    secao: "01",
    endpoint: "4_consultarItemMaterial",
    path: "/modulo-material/4_consultarItemMaterial",
    dto: "DmMaterialItemDTO",
    requiredKeys: ["codigoItem", "codigoPdm", "descricaoItem", "statusItem"],
    knownKeys: [
      "codigoItem",
      "codigoGrupo",
      "nomeGrupo",
      "codigoClasse",
      "nomeClasse",
      "codigoPdm",
      "nomePdm",
      "descricaoItem",
      "statusItem",
      "itemSustentavel",
      "codigo_ncm",
      "descricao_ncm",
      "aplica_margem_preferencia",
      "dataHoraAtualizacao",
    ],
    status: "fixture-ok",
    fixtureFile: "01/4_consultarItemMaterial.sample.json",
  },
  {
    secao: "01",
    endpoint: "5_consultarMaterialNaturezaDespesa",
    path: "/modulo-material/5_consultarMaterialNaturezaDespesa",
    dto: "DmMaterialNaturezaDespesaDTO",
    requiredKeys: ["codigoPdm", "codigoNaturezaDespesa"],
    knownKeys: [
      "codigoPdm",
      "codigoNaturezaDespesa",
      "nomeNaturezaDespesa",
      "statusNaturezaDespesa",
    ],
    status: "fixture-ok",
    fixtureFile: "01/5_consultarMaterialNaturezaDespesa.sample.json",
  },
  {
    secao: "01",
    endpoint: "6_consultarMaterialUnidadeFornecimento",
    path: "/modulo-material/6_consultarMaterialUnidadeFornecimento",
    dto: "DmMaterialUnidadeFornecimentoDTO",
    requiredKeys: ["codigoPdm", "siglaUnidadeFornecimento"],
    knownKeys: [
      "codigoPdm",
      "siglaUnidadeFornecimento",
      "nomeUnidadeFornecimento",
      "descricaoUnidadeFornecimento",
      "numeroSequencialUnidadeFornecimento",
      "siglaUnidadeMedida",
      "capacidadeUnidadeFornecimento",
      "statusUnidadeFornecimentoPdm",
      "statusUnidadeFornecimento",
      "dataHoraAtualizacao",
    ],
    status: "fixture-ok",
    fixtureFile: "01/6_consultarMaterialUnidadeFornecimento.sample.json",
  },
  {
    secao: "01",
    endpoint: "7_consultarMaterialCaracteristicas",
    path: "/modulo-material/7_consultarMaterialCaracteristicas",
    dto: "DmMaterialCaracteristicasDTO",
    requiredKeys: ["codigoItem", "nomeCaracteristica", "nomeValorCaracteristica"],
    knownKeys: [
      "codigoItem",
      "itemSustentavel",
      "statusItem",
      "codigoCaracteristica",
      "nomeCaracteristica",
      "statusCaracteristica",
      "codigoValorCaracteristica",
      "nomeValorCaracteristica",
      "statusValorCaracteristica",
      "numeroCaracteristica",
      "siglaUnidadeMedida",
      "dataHoraAtualizacao",
    ],
    status: "fixture-ok",
    fixtureFile: "01/7_consultarMaterialCaracteristicas.sample.json",
  },

  // --- 03 PESQUISA DE PREÇO ---
  {
    secao: "03",
    endpoint: "1_consultarMaterial",
    path: "/modulo-pesquisa-preco/1_consultarMaterial",
    dto: "FtPesqPrecoCompraMaterialDTO",
    requiredKeys: ["codigoItemCatalogo"],
    knownKeys: [
      "idCompra",
      "idItemCompra",
      "numeroItemCompra",
      "codigoItemCatalogo",
      "codigoPdm",
      "codigoClasse",
      "descricaoItem",
      "descricaoDetalhadaItem",
      "objetoCompra",
      "quantidade",
      "precoUnitario",
      "siglaUnidadeFornecimento",
      "nomeUnidadeFornecimento",
      "siglaUnidadeMedida",
      "dataCompra",
      "dataResultado",
      "niFornecedor",
      "nomeFornecedor",
      "codigoUasg",
      "nomeUasg",
      "codigoOrgao",
      "nomeOrgao",
      "estado",
      "municipio",
      "modalidade",
      "marca",
    ],
    status: "fixture-ok",
    fixtureFile: "03/1_consultarMaterial.sample.json",
  },
  {
    secao: "03",
    endpoint: "2_consultarMaterialDetalhe",
    path: "/modulo-pesquisa-preco/2_consultarMaterialDetalhe",
    dto: "FtPesqPrecoCompraMaterialDetalheDTO",
    requiredKeys: ["codigoItemCatalogo"],
    knownKeys: [
      "codigoItemCatalogo",
      "codigoPdm",
      "descricaoItem",
      "precoUnitario",
      "quantidade",
      "dataCompra",
      "niFornecedor",
      "nomeFornecedor",
      "codigoUasg",
      "nomeUasg",
    ],
    status: "fixture-ok",
    fixtureFile: "03/2_consultarMaterialDetalhe.sample.json",
  },

  // --- 04 PGC ---
  {
    secao: "04",
    endpoint: "2_consultarPgcDetalheCatalogo",
    path: "/modulo-pgc/2_consultarPgcDetalheCatalogo",
    dto: "FtPgcDetalheDTO",
    requiredKeys: [
      "codigoUasg",
      "codigoItemCatalogo",
      "anoPcaProjetoCompra",
    ],
    knownKeys: [
      "codigoUasg",
      "nomeUasg",
      "orgao",
      "numeroArtefato",
      "anoArtefato",
      "codigoEstadoArtefato",
      "codigoCategoriaArtefato",
      "descricaoArtefato",
      "codigoTipoArtefato",
      "ordemDfd",
      "descricaoObjetoDfd",
      "nivelPrioridadeDfd",
      "dataPrevistaFormalizacaoDemanda",
      "codigoAreaDfd",
      "tipoItem",
      "itemSustentavel",
      "codigoGrupoMaterial",
      "nomeGrupoMaterial",
      "codigoClasseMaterial",
      "nomeClasseMaterial",
      "codigoPdmMaterial",
      "nomePdmMaterial",
      "codigoSecaoServico",
      "nomeSecaoServico",
      "codigoDivisaoServico",
      "nomeDivisaoServico",
      "codigoGrupoServico",
      "nomeGrupoServico",
      "codigoClasseServico",
      "nomeClasseServico",
      "codigoSubclasseServico",
      "nomeSubclasseServico",
      "codigoItemCatalogo",
      "descricaoItemCatalogo",
      "siglaUnidadeFornecimento",
      "nomeUnidadeFornecimento",
      "quantidadeItem",
      "valorUnitarioItem",
      "valorTotalItem",
      "tituloProjetoCompra",
      "descricaoProjetoCompra",
      "anoPcaProjetoCompra",
      "dataInicioProcessoCompra",
      "dataFimProcessoCompra",
      "duracaoProcessoCompra",
      "numeroItemPncp",
      "statusContratacaoExecucao",
      "dataHoraPublicacaoPncp",
      "dataHoraAtualizacaoArtefato",
      "dataHoraAtualizacaoProjetoCompra",
      "dataHoraAtualizacaoDfd",
      "dataHoraAtualizacaoItem",
    ],
    status: "fixture-ok",
    fixtureFile: "04/2_consultarPgcDetalheCatalogo.sample.json",
  },

  // --- 05 UASG ---
  {
    secao: "05",
    endpoint: "1_consultarUasg",
    path: "/modulo-uasg/1_consultarUasg",
    dto: "DmCorpUasgDTO",
    requiredKeys: ["codigoUasg", "nomeUasg", "statusUasg"],
    knownKeys: [
      "codigoUasg",
      "nomeUasg",
      "usoSisg",
      "adesaoSiasg",
      "siglaUf",
      "codigoMunicipio",
      "codigoMunicipioIbge",
      "nomeMunicipioIbge",
      "codigoUnidadePolo",
      "nomeUnidadePolo",
      "codigoUnidadeEspelho",
      "nomeUnidadeEspelho",
      "uasgCadastradora",
      "cnpjCpfUasg",
      "codigoOrgao",
      "cnpjCpfOrgao",
      "cnpjCpfOrgaoVinculado",
      "cnpjCpfOrgaoSuperior",
      "codigoSiorg",
      "statusUasg",
      "dataImplantacaoSidec",
      "dataHoraMovimento",
    ],
    status: "fixture-ok",
    fixtureFile: "05/1_consultarUasg.sample.json",
  },
  {
    secao: "05",
    endpoint: "2_consultarOrgao",
    path: "/modulo-uasg/2_consultarOrgao",
    dto: "DmCorpOrgaoDTO",
    requiredKeys: ["codigoOrgao", "nomeOrgao", "statusOrgao"],
    knownKeys: [
      "codigoOrgao",
      "nomeOrgao",
      "nomeMnemonicoOrgao",
      "cnpjCpfOrgao",
      "codigoOrgaoVinculado",
      "cnpjCpfOrgaoVinculado",
      "nomeOrgaoVinculado",
      "codigoOrgaoSuperior",
      "cnpjCpfOrgaoSuperior",
      "nomeOrgaoSuperior",
      "codigoTipoAdministracao",
      "nomeTipoAdministracao",
      "poder",
      "esfera",
      "usoSisg",
      "statusOrgao",
      "dataHoraMovimento",
    ],
    status: "fixture-ok",
    fixtureFile: "05/2_consultarOrgao.sample.json",
  },

  // --- 06 LEGADO ---
  {
    secao: "06",
    endpoint: "1_consultarLicitacao",
    path: "/modulo-legado/1_consultarLicitacao",
    dto: "TbVwLicitacaoDTO",
    requiredKeys: ["id_compra", "uasg", "objeto"],
    knownKeys: [
      "id_compra",
      "identificador",
      "numero_processo",
      "uasg",
      "modalidade",
      "nome_modalidade",
      "numero_aviso",
      "situacao_aviso",
      "tipo_pregao",
      "tipo_recurso",
      "nome_responsavel",
      "funcao_responsavel",
      "numero_itens",
      "valor_estimado_total",
      "valor_homologado_total",
      "informacoes_gerais",
      "objeto",
      "endereco_entrega_edital",
      "codigo_municipio_uasg",
      "data_abertura_proposta",
      "data_entrega_edital",
      "data_entrega_proposta",
      "data_publicacao",
      "dt_alteracao",
      "pertence14133",
    ],
    status: "fixture-ok",
    fixtureFile: "06/1_consultarLicitacao.sample.json",
  },
  {
    secao: "06",
    endpoint: "2_consultarItemLicitacao",
    path: "/modulo-legado/2_consultarItemLicitacao",
    dto: "TbVwItemLicitacaoDTO",
    requiredKeys: ["id_compra", "numero_item_licitacao"],
    knownKeys: [
      "numero_licitacao",
      "uasg",
      "nome_uasg",
      "modalidade",
      "nome_modalidade",
      "numero_aviso",
      "numero_item_licitacao",
      "codigo_item_material",
      "nome_material",
      "codigo_item_servico",
      "nome_servico",
      "cnpj_fornecedor",
      "nome_fornecedor",
      "quantidade",
      "unidade",
      "descricao_item",
      "beneficio",
      "valor_estimado",
      "decreto_7174",
      "criterio_julgamento",
      "cpf_vencedor",
      "nome_vencedor_pf",
      "sustentavel",
      "dt_alteracao",
      "id_compra",
      "id_compra_item",
    ],
    status: "fixture-ok",
    fixtureFile: "06/2_consultarItemLicitacao.sample.json",
  },

  // --- stubs ---
  ...(["07", "08", "09", "10", "11", "97", "98", "99", "AUTENTICACAO"] as const).map(
    (secao): EndpointContract => ({
      secao,
      endpoint: "_stub",
      path: secao === "AUTENTICACAO" ? "/autenticacao" : `/modulo-${secao}`,
      dto: "TBD",
      requiredKeys: [],
      knownKeys: [],
      status: "nao-testado",
    }),
  ),
];

export function contractsForSecao(secao: string): EndpointContract[] {
  return CONTRACTS.filter((c) => c.secao === secao);
}

/** Seções que referenciam legislação (FK esperada em compras_api_secao_legislacao). */
export const SECOES_COM_LEGISLACAO: Record<
  string,
  { normas: string[]; papel: "rege" | "referencia" | "historico" }
> = {
  "03": { normas: ["IN SEGES/ME nº 65/2021"], papel: "referencia" },
  "04": { normas: ["Decreto nº 10.947/2022"], papel: "referencia" },
  "06": { normas: ["Lei nº 8.666/1993"], papel: "rege" },
  "07": { normas: ["Lei nº 14.133/2021"], papel: "rege" },
  "08": { normas: ["Decreto nº 11.462/2023"], papel: "rege" },
  "09": { normas: ["Lei nº 14.133/2021"], papel: "rege" },
};
